#!/bin/bash

clear

  cd /root
  rm *

  crontab -u root -r
  
clear

  a2enmod rewrite
  a2enmod expires
  a2enmod headers
  apt-get update
  apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y php5-curl php5-xsl php5-gd
  echo chitanka > /etc/hostname
  echo "Europe/Sofia" > /etc/timezone
  dpkg-reconfigure --frontend noninteractive tzdata

  line="127.0.1.1 lamp"
  rep="127.0.1.1 chitanka"
  sed -i "s/${line}/${rep}/g" /etc/hosts
clear

echo "Downloading..."
  wget -N http://download.chitanka.info/chitanka.sql.gz
  wget -N http://files.chitanka.info/maint
  wget -N http://files.chitanka.info/crtb
  wget -N http://files.chitanka.info/smb.conf
  wget -N http://files.chitanka.info/interfaces
  wget -N http://files.chitanka.info/gitconfconsole.py
  wget -N http://files.chitanka.info/shared
  wget -N http://files.chitanka.info/noshared
  wget -N http://files.chitanka.info/php.ini
  wget -N http://files.chitanka.info/gitservices.txt
  wget -N http://files.chitanka.info/gitsync
  wget -N http://files.chitanka.info/virthost
  
  mv -f shared /var/www
  mv -f noshared /var/www
  mv -f smb.conf /etc/samba
  mv -f maint /var/www/
  mv -f interfaces /etc/network
  mv -f gitconfconsole.py /usr/lib/confconsole/confconsole.py
  mv -f php.ini /etc/php5/apache2/
  mv -f gitsync /var/www
  mv -f gitservices.txt /etc/confconsole/services.txt
  mv -f virthost /etc/apache2/sites-available/chitanka
  chmod a+x /usr/lib/confconsole/confconsole.py
  gzip -d -f chitanka.sql.gz
  
clear
  
  echo "Starting system update procedure. Do not reboot or shutdown!"
  #apt-get update
  #apt-get upgrade -f -y
	
clear

  echo "Updating database..."
  echo "UPDATE text set removed_notice=null;" >> /root/chitanka.sql
  echo "UPDATE book set removed_notice=null;" >> /root/chitanka.sql
  echo "CREATE DATABASE IF NOT EXISTS chitanka CHARACTER SET utf8 COLLATE utf8_general_ci;" | mysql -uroot -pchitanka
  mysql -uroot -pchitanka chitanka < /root/chitanka.sql

clear
   
echo "Cloning..."
  mv /var/www/chitanka/web/content /root
  rm -fr /var/www/chitanka
  # git clone git://github.com/chitanka/chitanka-production.git chitanka
  # mv chitanka /var/www/
  # mv /root/content /var/www/chitanka/web
  
  git clone https://github.com/chitanka/chitanka-production.git /var/www/chitanka
  
  cd /var/www/chitanka
  #git pull
  cp /var/www/chitanka/app/config/parameters.yml.dist /var/www/chitanka/app/config/parameters.yml
  line="database_password:  ~"
  rep="database_password:  chitanka"
  sed -i "s/${line}/${rep}/g" /var/www/chitanka/app/config/parameters.yml
  line="exitWithMessage('maintenance');"
  rep=""
  sed -i "s/${line}/${rep}/g" /var/www/chitanka/web/index.php
  cd /var/www/chitanka
  chmod -R g+rw var/cache var/log var/spool web/cache
  chgrp -R www-data var/cache var/log var/spool web/cache

clear
  
echo "Synchronize content..."
echo $(date) > /var/www/chitanka/web/update.log
  #rsync -avz --delete rsync.chitanka.info::content/ /var/www/chitanka/web/content 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
  #echo $(date -I)/1 > /var/www/chitanka/update/db/.last
  mv /root/content /var/www/chitanka/web
  
    #sync book
  if [ ! -d /var/www/chitanka/web/content/book/.git ]
then
    git clone --depth=1 https://github.com/chitanka/content-book.git /var/www/chitanka/web/content/book
else
  cd /var/www/chitanka/web/content/book
  git pull 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
fi

#sync book-anno
  if [ ! -d /var/www/chitanka/web/content/book-anno/.git ]
then
    git clone --depth=1 https://github.com/chitanka/content-book-anno.git /var/www/chitanka/web/content/book-anno
else
  cd /var/www/chitanka/web/content/book-anno
  git pull 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
fi

#sync book-cover
  if [ ! -d /var/www/chitanka/web/content/book-cover/.git ]
then
    git clone --depth=1 https://github.com/chitanka/content-book-cover.git /var/www/chitanka/web/content/book-cover
else
  cd /var/www/chitanka/web/content/book-cover
  git pull 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
fi

#sync book-djvu
  if [ ! -d /var/www/chitanka/web/content/book-djvu/.git ]
then
    git clone --depth=1 https://github.com/chitanka/content-book-djvu.git /var/www/chitanka/web/content/book-djvu
else
  cd /var/www/chitanka/web/content/book-djvu
  git pull 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
fi

#sync book-img
  if [ ! -d /var/www/chitanka/web/content/book-img/.git ]
then
    git clone --depth=1 https://github.com/chitanka/content-book-img.git /var/www/chitanka/web/content/book-img
else
  cd /var/www/chitanka/web/content/book-img
  git pull 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
fi

#sync book-info
  if [ ! -d /var/www/chitanka/web/content/book-info/.git ]
then
    git clone --depth=1 https://github.com/chitanka/content-book-info.git /var/www/chitanka/web/content/book-info
else
  cd /var/www/chitanka/web/content/book-info
  git pull 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
fi

#sync book-pdf
  if [ ! -d /var/www/chitanka/web/content/book-pdf/.git ]
then
    git clone --depth=1 https://github.com/chitanka/content-book-pdf.git /var/www/chitanka/web/content/book-pdf
else
  cd /var/www/chitanka/web/content/book-pdf
  git pull 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
fi

#sync book-pic
  if [ ! -d /var/www/chitanka/web/content/book-pic/.git ]
then
    git clone --depth=1 https://github.com/chitanka/content-book-pic.git /var/www/chitanka/web/content/book-pic
else
  cd /var/www/chitanka/web/content/book-pic
  git pull 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
fi

#sync cover
  if [ ! -d /var/www/chitanka/web/content/cover/.git ]
then
    git clone --depth=1 https://github.com/chitanka/content-cover.git /var/www/chitanka/web/content/cover
else
  cd /var/www/chitanka/web/content/cover
  git pull 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
fi

#sync img
  if [ ! -d /var/www/chitanka/web/content/img/.git ]
then
    git clone --depth=1 https://github.com/chitanka/content-img.git /var/www/chitanka/web/content/img
else
  cd /var/www/chitanka/web/content/img
  git pull 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
fi

#sync misc
  if [ ! -d /var/www/chitanka/web/content/misc/.git ]
then
    git clone --depth=1 https://github.com/chitanka/content-misc.git /var/www/chitanka/web/content/misc
else
  cd /var/www/chitanka/web/content/misc
  git pull 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
fi

#sync text
  if [ ! -d /var/www/chitanka/web/content/text/.git ]
then
    git clone --depth=1 https://github.com/chitanka/content-text.git /var/www/chitanka/web/content/text
else
  cd /var/www/chitanka/web/content/text
  git pull 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
fi

#sync text-anno
  if [ ! -d /var/www/chitanka/web/content/text-anno/.git ]
then
    git clone --depth=1 https://github.com/chitanka/content-text-anno.git /var/www/chitanka/web/content/text-anno
else
  cd /var/www/chitanka/web/content/text-anno
  git pull 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
fi

#sync text-info
  if [ ! -d /var/www/chitanka/web/content/text-info/.git ]
then
    git clone --depth=1 https://github.com/chitanka/content-text-info.git /var/www/chitanka/web/content/text-info
else
  cd /var/www/chitanka/web/content/text-info
  git pull 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
fi

#sync user
  if [ ! -d /var/www/chitanka/web/content/user/.git ]
then
    git clone --depth=1 https://github.com/chitanka/content-user.git /var/www/chitanka/web/content/user
else
  cd /var/www/chitanka/web/content/user
  git pull 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
fi

#sync wiki
  if [ ! -d /var/www/chitanka/web/content/wiki/.git ]
then
    git clone --depth=1 https://github.com/chitanka/content-wiki.git /var/www/chitanka/web/content/wiki
else
  cd /var/www/chitanka/web/content/wiki
  git pull 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
fi

  
clear
  
echo "Synchronize database..."
  cd /var/www/chitanka; git stash 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log; git pull 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log; php bin/console auto-update --env=prod --skip-content --skip-src 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log

# echo Setting up crontab...
# crontab -u root crtb

clear

echo "Cleaning up..."
  apt-get autoclean
  apt-get clean
	
  cd /root
  rm *
  rm /update
  a2dissite *
  a2ensite chitanka
  
clear
echo "REBOOTING!"
reboot
