#!/bin/bash

clear
cd /root
rm *
  crontab -u root -r
  clear
echo chitanka > /etc/hostname
echo "Europe/Sofia" > /etc/timezone
dpkg-reconfigure --frontend noninteractive tzdata

  line="127.0.1.1 lamp"
  rep="127.0.1.1 chitanka"
  sed -i "s/${line}/${rep}/g" /etc/hosts
clear

clear

echo Downloading...
  wget -N http://download.chitanka.info/chitanka.sql.gz 2>/dev/null 1>/dev/null
  wget -N http://files.chitanka.nl/upgrd 2>/dev/null 1>/dev/null
  wget -N http://files.chitanka.nl/maint 2>/dev/null 1>/dev/null
  wget -N http://files.chitanka.nl/crtb 2>/dev/null 1>/dev/null
  wget -N http://files.chitanka.nl/smb.conf 2>/dev/null 1>/dev/null
  wget -N http://files.chitanka.nl/interfaces 2>/dev/null 1>/dev/null
  wget -N http://files.chitanka.nl/confconsole.py 2>/dev/null 1>/dev/null
  wget -N http://files.chitanka.nl/shared 2>/dev/null 1>/dev/null
  wget -N http://files.chitanka.nl/noshared 2>/dev/null 1>/dev/null
  wget -N http://files.chitanka.nl/php.ini 2>/dev/null 1>/dev/null
  wget -N http://files.chitanka.nl/services.txt 2>/dev/null 1>/dev/null
  mv -f shared /var/www
  mv -f noshared /var/www
  mv -f smb.conf /etc/samba
  mv -f maint /var/www/
  mv -f interfaces /etc/network
  mv -f confconsole.py /usr/lib/confconsole
  mv -f php.ini /etc/php5/apache2/
  mv -f services.txt /etc/confconsole
  chmod a+x /usr/lib/confconsole/confconsole.py
  gzip -d -f chitanka.sql.gz
  
  clear
  
  echo Starting system update procedure. Do not reboot or shutdown!
	dpkg -s apt-utils 2>/dev/null 1>/dev/null || sh upgrd
	clear
	debconf-apt-progress apt-get update; clear
	debconf-apt-progress apt-get upgrade -f -y; clear
	

echo "Updating database..."
echo "UPDATE text set removed_notice=null;" >> /root/chitanka.sql
echo "UPDATE book set removed_notice=null;" >> /root/chitanka.sql
mysql -uroot -pchitanka chitanka < /root/chitanka.sql

   clear
   
echo "Cloning..."

  mv /var/www/chitanka/web/content /root
  rm -fr /var/www/chitanka
  git clone git://gitorious.org/chitanka/chitanka-production.git chitanka
  mv chitanka /var/www/
  mv /root/content /var/www/chitanka/web
  cp /var/www/chitanka/app/config/parameters.yml.dist /var/www/chitanka/app/config/parameters.yml
  line="database_password:  ~"
  rep="database_password:  chitanka"
  sed -i "s/${line}/${rep}/g" /var/www/chitanka/app/config/parameters.yml
  line="exitWithMessage('maintenance');"
  rep=""
  sed -i "s/${line}/${rep}/g" /var/www/chitanka/web/index.php
  cd /var/www/chitanka
  chmod -R g+rw var/cache var/log var/spool web/cache
  chgrp -R www-data var/cache var/log var/spool web/cache

  clear
echo "Synchronize content..."

  rsync -avz --delete rsync.chitanka.info::content/ /var/www/chitanka/web/content
  echo $(date -I)/1 > /var/www/chitanka/update/db/.last
  
  clear
echo "Synchronize database..."  

  cd /var/www/chitanka; git stash; git pull; php bin/console auto-update --env=prod --skip-content --skip-src

echo Setting up crontab...

cd /root
# crontab -u root crtb

clear
	apt-get autoclean
	apt-get clean
rm * &> /dev/null
rm /update &> /dev/null
clear
reboot
