#!/bin/bash

clear

  cd /root
  rm *

  crontab -u root -r
  
clear

  echo chitanka > /etc/hostname
  echo "Europe/Sofia" > /etc/timezone > /var/www/chitanka/web/update.log
  dpkg-reconfigure --frontend noninteractive tzdata > /var/www/chitanka/web/update.log

  line="127.0.1.1 lamp"
  rep="127.0.1.1 chitanka"
  sed -i "s/${line}/${rep}/g" /etc/hosts
clear

echo "Downloading..."
  wget -N http://download.chitanka.info/chitanka.sql.gz > /var/www/chitanka/web/update.log
  wget -N http://files.chitanka.info/maint > /var/www/chitanka/web/update.log
  wget -N http://files.chitanka.info/crtb > /var/www/chitanka/web/update.log
  wget -N http://files.chitanka.info/smb.conf > /var/www/chitanka/web/update.log
  wget -N http://files.chitanka.info/interfaces > /var/www/chitanka/web/update.log
  wget -N http://files.chitanka.info/confconsole.py > /var/www/chitanka/web/update.log
  wget -N http://files.chitanka.info/shared > /var/www/chitanka/web/update.log
  wget -N http://files.chitanka.info/noshared > /var/www/chitanka/web/update.log
  wget -N http://files.chitanka.info/php.ini > /var/www/chitanka/web/update.log
  wget -N http://files.chitanka.info/services.txt > /var/www/chitanka/web/update.log
  
  mv -f shared /var/www
  mv -f noshared /var/www
  mv -f smb.conf /etc/samba
  mv -f maint /var/www/
  mv -f interfaces /etc/network
  mv -f confconsole.py /usr/lib/confconsole
  mv -f php.ini /etc/php5/apache2/
  mv -f services.txt /etc/confconsole
  chmod a+x /usr/lib/confconsole/confconsole.py
  gzip -d -f chitanka.sql.gz
  
clear
  
  echo "Starting system update procedure. Do not reboot or shutdown!"
  apt-get update > /var/www/chitanka/web/update.log
  dpkg --configure -a >> /var/www/chitanka/web/update.log
  apt-get upgrade -f -y >> /var/www/chitanka/web/update.log
	
clear

  echo "Updating database..."
  echo "UPDATE text set removed_notice=null;" >> /root/chitanka.sql
  echo "UPDATE book set removed_notice=null;" >> /root/chitanka.sql
  mysql -uroot -pchitanka chitanka < /root/chitanka.sql

clear
   
echo "Cloning..."
  mv /var/www/chitanka/web/content /root
  mv /var/www/chitanka/web/update.log /root
  rm -fr /var/www/chitanka
  git clone git://github.com/chitanka/chitanka-production.git chitanka > /root/update.log
  mv chitanka /var/www/
  mv /root/content /var/www/chitanka/web
  mv /root/update.log /var/www/chitanka/web/
  cp /var/www/chitanka/app/config/parameters.yml.dist /var/www/chitanka/app/config/parameters.yml
  line="database_password:  ~"
  rep="database_password:  chitanka"
  sed -i "s/${line}/${rep}/g" /var/www/chitanka/app/config/parameters.yml
  line="exitWithMessage('maintenance');"
  rep=""
  sed -i "s/${line}/${rep}/g" /var/www/chitanka/web/index.php
  cd /var/www/chitanka
  chmod -R g+rw var/cache var/log var/spool web/cache
  chgrp -R www-data var/cache var/log var/spool web/cache

clear
  
echo "Synchronize content..."
echo $(date) > /var/www/chitanka/web/update.log
  rsync -avz --delete rsync.chitanka.info::content/ /var/www/chitanka/web/content 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
  echo $(date -I)/1 > /var/www/chitanka/update/db/.last
  
clear
  
echo "Synchronize database..."
  cd /var/www/chitanka; git stash 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log; git pull 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log; php bin/console auto-update --env=prod --skip-content --skip-src 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log

# echo Setting up crontab...
# crontab -u root crtb

clear

echo "Cleaning up..."
  apt-get autoclean > /var/www/chitanka/web/update.log
  apt-get clean > /var/www/chitanka/web/update.log
	
  cd /root
  rm *
  rm /update > /var/www/chitanka/web/update.log
  
clear
echo "REBOOTING!"
reboot
