#!/bin/bash

clear

  cd /root
  rm *

  crontab -u root -r
  
clear

  echo chitanka > /etc/hostname
  echo "Europe/Sofia" > /etc/timezone 2>/dev/null 1>/dev/null
  dpkg-reconfigure --frontend noninteractive tzdata 2>/dev/null 1>/dev/null
  cd /var/www/chitanka
  # git config --global user.email "chitanka@local"
  # git config --global user.name "chitanka"
  cd /root

  line="127.0.1.1 lamp"
  rep="127.0.1.1 chitanka"
  sed -i "s/${line}/${rep}/g" /etc/hosts
clear

echo "Downloading..."
  wget -N http://download.chitanka.info/chitanka.sql.gz 2>/dev/null 1>/dev/null
  wget -N https://raw.githubusercontent.com/chitanka/sites-files/master/maint 2>/dev/null 1>/dev/null
  wget -N https://raw.githubusercontent.com/chitanka/sites-files/master/crtb 2>/dev/null 1>/dev/null
  wget -N https://raw.githubusercontent.com/chitanka/sites-files/master/smb.conf 2>/dev/null 1>/dev/null
  wget -N https://raw.githubusercontent.com/chitanka/sites-files/master/interfaces 2>/dev/null 1>/dev/null
  wget -N https://raw.githubusercontent.com/chitanka/sites-files/master/confconsole.py 2>/dev/null 1>/dev/null
  wget -N https://raw.githubusercontent.com/chitanka/sites-files/master/shared 2>/dev/null 1>/dev/null
  wget -N https://raw.githubusercontent.com/chitanka/sites-files/master/noshared 2>/dev/null 1>/dev/null
  wget -N https://raw.githubusercontent.com/chitanka/sites-files/master/php.ini 2>/dev/null 1>/dev/null
  wget -N https://raw.githubusercontent.com/chitanka/sites-files/master/services.txt 2>/dev/null 1>/dev/null
  
  mv -f shared /var/www
  mv -f noshared /var/www
  mv -f smb.conf /etc/samba
  mv -f maint /var/www/
  mv -f interfaces /etc/network
  mv -f confconsole.py /usr/lib/confconsole
  cp -fr php.ini /etc/php/7.0/apache2/
  mv -f php.ini /etc/php/7.0/cli/
  mv -f services.txt /etc/confconsole
  chmod a+x /usr/lib/confconsole/confconsole.py
  gzip -d -f chitanka.sql.gz
  
clear
  
# echo "Starting system update procedure. Do not reboot or shutdown!"
#  apt-get update 2>/dev/null 1>/dev/null
#  apt-get upgrade -f -y 2>/dev/null 1>/dev/null
	
clear
 
  mysqladmin -uroot -pchitanka -f drop chitanka 2>/dev/null 1>/dev/null;
  mysqladmin -uroot -pchitanka create chitanka 2>/dev/null 1>/dev/null;
  echo "Updating database..."
  echo "UPDATE text set removed_notice=null;" >> /root/chitanka.sql
  echo "UPDATE book set removed_notice=null;" >> /root/chitanka.sql
  mysql -uroot -pchitanka chitanka < /root/chitanka.sql

clear
   
echo "Cloning..."
  mv /var/www/chitanka/web/content /root 2>/dev/null 1>/dev/null
  rm -fr /var/www/chitanka
  git clone git://github.com/chitanka/chitanka-production.git chitanka 2>/dev/null 1>/dev/null
  rm -fr chitanka/web/content
  mv chitanka /var/www/
  mv /root/content /var/www/chitanka/web/
  echo $(date) > /var/www/chitanka/web/update.log
  cp /var/www/chitanka/app/config/parameters.yml.dist /var/www/chitanka/app/config/parameters.yml
  line="database_password:  ~"
  rep="database_password:  chitanka"
  sed -i "s/${line}/${rep}/g" /var/www/chitanka/app/config/parameters.yml
  line="exitWithMessage('maintenance');"
  rep=""
  sed -i "s/${line}/${rep}/g" /var/www/chitanka/web/index.php
  cd /var/www/chitanka
  # git stash; git pull
  chmod -R g+rw var/cache var/log var/spool web/cache
  chgrp -R www-data var/cache var/log var/spool web/cache

clear
  
echo "Synchronize content..."
  rsync -avz --delete rsync.chitanka.info::content/ /var/www/chitanka/web/content 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log
  echo $(date -I)/1 > /var/www/chitanka/update/db/.last
  
clear
  
echo "Synchronize database..."
  cd /var/www/chitanka; php bin/console auto-update --env=prod --skip-content --skip-src 2>>/var/www/chitanka/web/update.log 1>>/var/www/chitanka/web/update.log

# echo Setting up crontab...
# crontab -u root crtb

clear

# echo "Cleaning up..."
  # apt-get autoclean
  # apt-get clean
	
  cd /root
  rm *
  rm /update
  
clear
echo "REBOOTING!"
reboot
